# Generated by Django 4.0.2 on 2022-02-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hide_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=models.CharField(choices=[('1', 'IT and Networks'), ('2', 'UI/UX'), ('3', 'Web Development'), ('4', 'Devops')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
