# Generated by Django 4.0.2 on 2022-02-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_customuser_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=models.CharField(choices=[('IT and Networks', 'IT and Networks'), ('UI/UX', 'UI/UX'), ('Web Development', 'Web Development'), ('Devops', 'Devops')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='user_photos/nouser.jpg', max_length=255, upload_to='user_photos'),
        ),
    ]
